### ISSUE TITLE
line2route fails if n_processes=1 or the number of lines is 1

### ISSUE THREAD

**Issue by AnnaGoodman1** [ropensci/stplanr#191] opened 2017-05-30 09:21 UTC
In either case on gets the error message:

**Error in line2route(l = routes_redo, route_fun = route_cyclestreet, plan = route_type,  : 
  object 'r' not found
In addition: Warning message:
In value[[3L]](cond) : Fail for line number 1**

I think possibly something is going wrong in lines 305-307 of https://github.com/ropensci/stplanr/blob/master/R/od-funs.R ?  (also in line 308 n_print does not seem defined?).  Or may be something else.

I appreciate one usually routes in batches, but doing a single line is useful if one is mopping up random failed lines within a batch (e..g 1 of 5000 failed) so if this could be fixed that would be great. Thanks @Robinlovelace

**Comment by Robinlovelace** [comment] 2017-05-30 09:47
Here is a reproducible example of that (makes confirming and fixing issues easier):

``` r
devtools::install_github("ropensci/stplanr")
#> Skipping install of 'stplanr' from a github remote, the SHA1 (f1678b5e) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(stplanr)
#> Loading required package: sp
l = points2line(p = matrix(c(50, 51, 0, 0), ncol = 2))
r = line2route(l)
#> Warning in value[[3L]](cond): Fail for line number 1
#> Error in r@data[i, "error"] <- rc[[i]][1]: object 'r' not found
```

Cheers for reporting - not a serious one but certainly worth fixing and will make `line2route` easier for use on single lines.

**Comment by Robinlovelace** [comment] 2017-05-30 09:52
As a work-around you could try this:

```r
lp = line2points(l)
r = route_cyclestreet(lp[1,], lp[2,])
```

Resulting in this:

![image](https://cloud.githubusercontent.com/assets/1825120/26577931/fa3cdaf4-4525-11e7-833c-e439a624d564.png)

**Comment by Robinlovelace** [comment] 2017-05-30 10:12
Update - I cannot reproduce the issue using the development version so closing for now.

Please reproduce and let us know if you're still having issues:

``` r
# devtools::install_github('ropensci/stplanr')
library(stplanr)
#> Loading required package: sp
library(tmap)
l = line2route(flowlines[2, ])
r = line2route(l)
qtm(r)
```

![](http://i.imgur.com/JTa2SNC.png)

**Comment by AnnaGoodman1** [comment] 2017-05-30 13:24
Hi @Robinlovelace , Thanks for having a look, but I do still get the same error you initially got when trying that code:
![untitled](https://cloud.githubusercontent.com/assets/11818225/26585057/edbd749c-4542-11e7-8c42-bda7fbe08234.png)


or ditto same errors (because your code seemed to apply line2route twice?) when trying the variant :
devtools::install_github('ropensci/stplanr')
library(stplanr)
#> Loading required package: sp
library(tmap)
l =flowlines[2, ]
r = line2route(l)
qtm(r)

**Comment by Robinlovelace** [comment] 2017-05-30 13:26
Interesting - thanks for reproducing. Re-opening for now, strange that it's working on my computer but not yours.

**Comment by Robinlovelace** [comment] 2017-05-30 13:30
From a new R session:

![image](https://cloud.githubusercontent.com/assets/1825120/26585604/8564c04c-4544-11e7-9cef-d1d63a5fafef.png)

**Comment by Robinlovelace** [comment] 2017-05-30 13:33
My only suggestion at this stage would be to ensure you're running the latest version or R and ensure your packages are up-to-date, e.g. with:

```r
update.packages
```

(Incidentally to print code in a comment you can use '[backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)' to improve readability - or the [reprex](https://github.com/tidyverse/reprex) package is great for producing reproducible examples).

**Comment by AnnaGoodman1** [comment] 2017-05-30 13:54
yes, odd - well, thanks for trying!  Anna

**Comment by Robinlovelace** [comment] 2017-05-30 14:24
Please could you confirm that this does not fail:

```r
library(stplanr)
#> Loading required package: sp
library(tmap)
l =flowlines[2:5, ]
```

To ensure that it's not failing for many lines?

**Comment by mpadge** [comment] 2017-05-30 15:49
It all works well for me on
```
> packageVersion("stplanr")
[1] ‘0.1.7.3’
> packageVersion("tmap")                                                                                                                
[1] ‘1.10’
> Sys.info()
sysname 
"Linux" 
release 
"4.8.0-53-generic" 
version 
"#56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017" 
```
But note a separate issue, starting with a fresh R session
```
> l <- stplanr::line2route (stplanr::flowlines [2, ])
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'route_cyclestreet' of mode 'function' was not found
```
But works if full `stplanr` namespace loaded
```
> require (stplanr)
> l <- stplanr::line2route (stplanr::flowlines [2, ])
```
Want me to open a separate issue on that one?

**Comment by Robinlovelace** [comment] 2017-05-30 15:55
No because you could have set the function and the necessary data is only loaded (lazily) after it's loaded so I think that's a non-issue. Thanks for testing - I'm closing this issue for now but if others can reproduce the behaviour reported by @AnnaGoodman1 will happily re-open.

Many thanks for testing - it's led to a load of changes that will hopefully be merged in and published on CRAN as version 0.1.8 soon: https://github.com/ropensci/stplanr/pull/192

**Comment by richardellison** [comment] 2017-05-31 06:01
Reopening as I can reproduce on my laptop running Linux as well but an older release of R (so not just a strange Windows issue):

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8       
 [4] LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stplanr_0.1.7-3 sp_1.2-4       

loaded via a namespace (and not attached):
 [1] igraph_1.0.1        Rcpp_0.12.8         raster_2.5-2        magrittr_1.5       
 [5] maptools_0.8-40     doParallel_1.0.8    geosphere_1.4-3     lattice_0.20-33    
 [9] R6_2.2.0            foreach_1.4.2       stringr_1.1.0       plyr_1.8.3         
[13] httr_1.2.1          dplyr_0.5.0         tools_3.2.2         parallel_3.2.2     
[17] rgdal_1.2-5         grid_3.2.2          R.oo_1.19.0         png_0.1-7          
[21] DBI_0.5             rgeos_0.3-21        iterators_1.0.7     lazyeval_0.2.0     
[25] digest_0.6.8        assertthat_0.1      tibble_1.2          RJSONIO_1.3-0      
[29] readr_1.0.0         R.utils_2.1.0       codetools_0.2-14    curl_2.3           
[33] memoise_0.2.1       openxlsx_3.0.0      stringi_1.0-1       RgoogleMaps_1.2.0.7
[37] R.methodsS3_1.7.0   lubridate_1.3.3     jsonlite_1.2        foreign_0.8-66 


l = line2route(flowlines[2,])
Updating CYCLESTREET environment variable. Save this to .Renviron for future use.
Error in r@data[i, "error"] <- rc[[i]][1] : object 'r' not found
In addition: Warning message:
In value[[3L]](cond) : Fail for line number 1
```

@AnnaGoodman1 Can you please paste the output of `sessionInfo()`?

**Comment by richardellison** [comment] 2017-05-31 07:35
It does seem to work on Windows however, with the following versions:

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stplanr_0.1.8 sp_1.2-4     

loaded via a namespace (and not attached):
 [1] igraph_1.0.1      Rcpp_0.12.11      raster_2.5-8      knitr_1.15.1      magrittr_1.5      maptools_0.9-2    devtools_1.12.0  
 [8] doParallel_1.0.10 geosphere_1.5-5   lattice_0.20-33   R6_2.2.0          foreach_1.4.3     stringr_1.2.0     dplyr_0.5.0      
[15] httr_1.2.1        tools_3.3.1       parallel_3.3.1    rgdal_1.2-7       grid_3.3.1        R.oo_1.21.0       png_0.1-7        
[22] DBI_0.5-1         git2r_0.18.0      withr_1.0.2       rgeos_0.3-23      iterators_1.0.8   lazyeval_0.2.0    assertthat_0.1   
[29] digest_0.6.12     tibble_1.2        R.utils_2.5.0     codetools_0.2-14  curl_1.1          memoise_1.0.0     openxlsx_4.0.17  
[36] stringi_1.1.5     RgoogleMaps_1.4.1 R.methodsS3_1.7.1 jsonlite_1.4      foreign_0.8-66   
```

**Comment by richardellison** [comment] 2017-05-31 07:39
Running the current version on GitHub (after merging Robin's latest commits), still fails on my laptop:

```
> l = line2route(flowlines[2,])
Error in r@data[i, "error"] <- rc[[i]][1] : object 'r' not found
In addition: Warning message:
In value[[3L]](cond) : Fail for line number 1
```

With the following `sessionInfo()`:
```
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8       
 [4] LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stplanr_0.1.8 sp_1.2-4     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8         lattice_0.20-33     codetools_0.2-14    png_0.1-7          
 [5] foreach_1.4.2       R.methodsS3_1.7.0   grid_3.2.2          DBI_0.5            
 [9] magrittr_1.5        RgoogleMaps_1.2.0.7 geosphere_1.4-3     raster_2.5-2       
[13] doParallel_1.0.8    R.oo_1.19.0         R.utils_2.1.0       openxlsx_3.0.0     
[17] rgdal_1.2-5         iterators_1.0.7     RJSONIO_1.3-0       tools_3.2.2        
[21] foreign_0.8-66      igraph_1.0.1        parallel_3.2.2      maptools_0.8-40    
[25] rgeos_0.3-21   
```

**Comment by richardellison** [comment] 2017-05-31 07:43
On further testing, this seems to be an intermittent issue. One the same laptop that failed above, I just had the following occur:

```
l = line2route(flowlines[2,])
Error in r@data[i, "error"] <- rc[[i]][1] : object 'r' not found
In addition: Warning message:
In value[[3L]](cond) : Fail for line number 1
> l = line2route(flowlines[2,])
NOTE: rgdal::checkCRSArgs: no proj_defs.dat in PROJ.4 shared files
> l = line2route(flowlines[2,])
NOTE: rgdal::checkCRSArgs: no proj_defs.dat in PROJ.4 shared files
> l
class       : SpatialLinesDataFrame 
features    : 1 
extent      : -1.535617, -1.516734, 53.82847, 53.82887  (xmin, xmax, ymin, ymax)
coord. ref. : +init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
variables   : 17
names       : plan, start, finish, length, time, waypoint, cum_hill, change_elev, dif_max_min, up_tot, down_tot,         av_incline, co2_saving, calories, busyness, ... 
min values  :    1,     1,      1,   1535,  464,       53,       87,          -7,          39,     40,       47, 0.0566775244299674,        286,       52,     3327, ... 
max values  :    1,     1,      1,   1535,  464,       53,       87,          -7,          39,     40,       47, 0.0566775244299674,        286,       52,     3327, ... 
```

**Comment by Robinlovelace** [comment] 2017-05-31 08:03
Strange. Any ideas? I think the code could be refactored and improved but can't see the cause.

**Comment by richardellison** [comment] 2017-06-02 01:56
Not sure but I wonder if when the connection to the server fails for some reason we end up with this result because R just continues as if it succeeded. We could add some simple error checking but this does not necessarily resolve the underlying problem if it is something more inherent in stplanr.

**Comment by Robinlovelace** [comment] 2017-06-02 07:54
Hmm I think the checking code could be better, but I'm getting not issue. I just tried the following code and it worked 10:10 times:


```r
library(stplanr)
l = flowlines[2,]
r = line2route(l)
r = line2route(l)
r = line2route(l)
r = line2route(l)
r = line2route(l)
r = line2route(l)
r = line2route(l)
r = line2route(l)
r = line2route(l)
r = line2route(l)
```

@AnnaGoodman1 and @richardellison could you try running that and report back what % time it's failing?

Thanks.

**Comment by richardellison** [comment] 2017-06-02 10:28
In my case I think it is a result of a sometimes flaky WiFi connection at the university. I have a similar issue sometimes when I'm trying to push to a repo and I get an error saying I don't have the necessary permissions. Trying again normally works.

**Comment by Robinlovelace** [comment] 2017-06-02 10:32
OK, closing again in that case. Any updates on your attempts @AnnaGoodman1 very welcome. Thanks for reporting in any case, has led to some good testing and a few improvements, even if it didn't seem to have addressed the specific issue.

**Closed by Robinlovelace** 2017-06-02 10:32 UTC
