### ISSUE TITLE
Make use of my own network in stplanr, assign node IDs and retrieve paths

### ISSUE THREAD

**Issue by mnist91** [ropensci/stplanr#391] opened 2020-04-21 09:43 UTC
Dear developers,
I have tried to use the `stplanr` functionality on my own network. Unfortunately, I failed to figure out how to perform some necessary steps within `stplanr`. Would you mind to take a look at my question on [stackoverflow](https://stackoverflow.com/q/61327629/8107362)?
It's about how to convert my data to the correct format, assign node IDs, and retrieve network routes. 
Any help is much appreciated :)

**Comment by mpadge** [comment] 2020-04-21 10:38
@mnist91 You can do what you want with the [`dodgr` package](https://github.com/atfutures/dodgr), noting that:

1. `dodgr` expects its own input formats, so you'll note i've slightly renamed a couple of your columns.
2. Vertices in `dodgr` networks are labelled, and so `from` and `to` are passed as characters, not integers (`"101"`, not `101`).


``` r
library (dodgr)
routes <- data.frame(from_x = c(1, 3, 3, 2, 1),
                     from_y = c(3, 3, 2, 1, 3),
                     to_x = c(3, 3, 2, 1, 3),
                     to_y = c(3, 2, 1, 3, 2),
                     from_id = c(101, 102, 103, 104, 101),
                     to_id = c(102, 103, 104, 101, 103),
                     id_edge = 1:5,
                     distance = c(2.1, 1, 1.5, 2.5, 10))
dodgr_paths (routes, from = "101", to = "103")
#> $`101`
#> $`101`$`101-103`
#> [1] "101" "102" "103"
dodgr_dists (routes, from = "101", to = "103")
#>     103
#> 101 3.1
routes$d_weighted <- routes$distance
routes$d_weighted [routes$from_id == 101 & routes$to_id == 103] <- 2
dodgr_paths (routes, from = "101", to = "103")
#> $`101`
#> $`101`$`101-103`
#> [1] "101" "103"
dodgr_dists (routes, from = "101", to = "103")
#>     103
#> 101  10
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`dodgr` is intended to work with weighted graphs. The first call to `dodgr_paths` receives a graph with `distance` only, so the path is calculated using those values. The addition of a `d_weighted` column then means that the route will be calculated using those values, but if you actually calculate the resultant distance, that will use the original `distance` values. So `d_weighted` values will determine *where* you go, while actual distances will always be calculated from your original `distance` values.

I'm pasting this here because your SO Q explicitly asked how to do this in `stplanr`, so this answer should not be posted there (unless you want to modify the wording of your question). And now over to you @Robinlovelace to provide the definitive answer... :rocket:

**Comment by mnist91** [comment] 2020-04-21 11:10
Thanks a lot for your answer, @mpadge!
I already came across `dodgr` and wanted to compare it to `stplanr`. Its integration of `sf` objects seemed promising to me yet I was not able to reproduce the results from `dodgr`, therefore my question. 
Again, I really appreciate your detailed answer 🙂

**Comment by agila5** [comment] 2020-04-26 23:25
Hi! I'm sorry that I totally missed this interesting issue but I think I almost solved the problem. The solution is extremely long and convoluted and I'd like to discuss here how to proceed. 

Anyway, the following code is used to recreate your problem. It's a slightly modified version of the code you posted on SO. I translated the `sp` code to `sf` since 1) I'm not familiar with `sp` and 2) at the beginning I thought that the problem was related to `sp` (but this is not the case). Moreover, the code is not exactly the same as the SO code since ``stplanr:::`weightfield<-`()`` is bugged for `sf` objects (more details at the end of this comment), but that's irrelevant now.  

``` r
# packages
library(stplanr)
library(sf)
library(igraph)

# Create the network structure 
routes <- st_sf(
  ID_from = c(101, 102, 103, 104, 101),
  ID_to = c(102, 103, 104, 101, 103), 
  ID_edge = 1:5, 
  distance = c(2.1, 1, 1.5, 2.5, 10),
  geometry = st_sfc(
    st_linestring(rbind(c(1, 3), c(3, 3))), 
    st_linestring(rbind(c(3, 3), c(3, 2))), 
    st_linestring(rbind(c(3, 2), c(2, 1))), 
    st_linestring(rbind(c(2, 1), c(1, 3))), 
    st_linestring(rbind(c(1, 3), c(3, 2)))
  )
)

# This is the result
routes
#> Simple feature collection with 5 features and 4 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 1 xmax: 3 ymax: 3
#> CRS:            NA
#>   ID_from ID_to ID_edge distance              geometry
#> 1     101   102       1      2.1 LINESTRING (1 3, 3 3)
#> 2     102   103       2      1.0 LINESTRING (3 3, 3 2)
#> 3     103   104       3      1.5 LINESTRING (3 2, 2 1)
#> 4     104   101       4      2.5 LINESTRING (2 1, 1 3)
#> 5     101   103       5     10.0 LINESTRING (1 3, 3 2)

# Create the sfNetwork object
sln <- SpatialLinesNetwork(routes)
plot(sln)
```

![](https://i.imgur.com/clVkp6d.png)

The first vertex, which is named "101", is at the top left of the plot; the second vertex, which is named "102", is at the top right; the third vertex, which is named "103",  is below the second vertex and the fourth vertex, which is named "104", is at the bottom of the plot. The first edge is from "101" to "102" and so on. 

Then I run the "shortest path" code and everything is fine: 

``` r
# Modify the IDs 
V(sln@g)$name <- as.character(101:104)

# shortest path 
(shortest <- sum_network_routes(sln = sln, 
                                start = "101", end = "103", 
                                sumvars = c("length")))
#> Simple feature collection with 1 feature and 3 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 2 xmax: 3 ymax: 3
#> CRS:            NA
#> # A tibble: 1 x 4
#>       geometry    ID sum_length pathfound
#>   <LINESTRING> <dbl>      <dbl> <lgl>    
#> 1   (3 2, 1 3)     1       2.24 TRUE

plot(st_geometry(sln@sl))
plot(st_geometry(shortest), add = TRUE, col = "red", lwd = 2)
```

![](https://i.imgur.com/dge314W.png)

Then I tested the "most efficient" code and there was a problem: 
``` r
# fastest path
E(sln@g)$weight <- routes$distance
sln@sl$length <- routes$distance

(most_efficient <- sum_network_routes(sln = sln, 
                                      start = "101", end = "103", 
                                      sumvars = c("length")))
#> Simple feature collection with 1 feature and 3 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 3 xmax: 3 ymax: 3
#> CRS:            NA
#> # A tibble: 1 x 4
#>               geometry    ID sum_length pathfound
#>           <LINESTRING> <dbl>      <dbl> <lgl>    
#> 1 (3 3, 1 3, 3 3, 3 3)     1        3.1 TRUE
plot(st_geometry(sln@sl))
plot(st_geometry(shortest), add = TRUE, col = "red", lwd = 2)
plot(st_geometry(most_efficient), add = TRUE, col = "blue", lwd = 2)
```

![](https://i.imgur.com/RFWVC4M.png)

Please note that I had to apply a small trick to change the weights of the `sln` object but that's unrelated to the problem since it's the same code used by ``stplanr:::`weightfield<-`()`` function. 

So I run the `sum_network_routes` function in debug mode and I found that, after several checks, the important evaluations occur here: 

https://github.com/ropensci/stplanr/blob/820791d679a9ef0359e71308d6b862829d1068ad/R/SpatialLinesNetwork.R#L542-L545

and here (and maybe later, IDK, but for sure there are some problems here): 

https://github.com/ropensci/stplanr/blob/820791d679a9ef0359e71308d6b862829d1068ad/R/SpatialLinesNetwork.R#L547-L565

The first object, `routesegs`, stores the ID(s) of the edge(s) that form the shortest path. For example, in the "shortest" case, I obtain that `routesegs` is a list of 1 element (since we asked for just one path, from "101" to "103") and its only element is the number 5 (since the shortest path between "101" and "103" is the fifth edge). In the "most efficient" case, `routesegs` is a list of 1 element (since we asked for just one path), where its only element is a vector of two numbers: 1 and 2. This means that the "most efficient" path between "101" and "103" is going through the first edge and then through the second edge (and it should be the correct path, right?). 

The second object, `routecoords`, is used to store the coordinates of the route. If we run the `mapply` code line by line we obtain that, in the "shortest" case, 
```
routesegs
[[1]]
[1] 5
```
so 
```
(linecoords <- sf::st_coordinates(sln@sl[routesegs[[1]], ]))
     X Y L1
[1,] 1 3  1
[2,] 3 2  1 
```
and these are the coordinates of the points of the fifth edge. The following lines are used to format the `linecoords` object as a list of matrix of coordinates (according to the `"L1"` columns): 

```
(linecoords <- lapply(1:max(linecoords[, "L1"]), function(x) {
+   linecoords[which(linecoords[, "L1"] == x), ]
+ }))
[[1]]
     X Y L1
[1,] 1 3  1
[2,] 3 2  1
```
Now there are some problems. In fact, when we run part of the next line
```
sln@g$x[start]; sln@g$y[start]
[1] NA
[1] NA
```
and this is a problem since `sln@g$x[start]` and `sln@g$y[start]` are the inputs of the `join_spatiallines_coords_sf` function (I don't understand its code since it's in C++ and I cannot predict its behaviour when the inputs are NA).  But why? The problem is that the slot `g` of the `SpatialLinesNetwork` function is an `igraph` object with several attributes, i.e.: 
```
sln@g
IGRAPH a96ed54 UNW- 4 5 -- 
+ attr: x (g/n), y (g/n), n (g/n), name (v/c), weight (e/n)
+ edges from a96ed54 (vertex names):
[1] 101--102 102--103 103--104 101--104 101--103
```
The attributes `x` and `y` store the x and y coordinates of the vertices, the `weight` attributes is used for _shortest_paths_ (and the `e` means that it's for the edges), the `n` attribute counts the number of neighbours for each vertex (which are detailed by the `sln@nb` slot), while we set the `name` attribute (just for the vertices) at the beginning of the script. In fact: 

``` 
sln@g$x; sln@g$y; sln@g$n; V(sln@g)$name; E(sln@g)$weight
[1] 1 3 3 2
[1] 3 3 2 1
[1] 3 2 3 2
[1] "101" "102" "103" "104"
[1]  2.1  1.0  1.5  2.5 10.0
``` 

Anyway, long story short, the problem here is that the `sln@g$x[start]` and `sln@g$y[start]` code assume that `start` is the numeric index of the vertex and, in both cases, `sln@g$x/y` is not a named vector so `sln@g$x["101"] = NA`. I don't understand the C++ code but I think that this means that the fact that the shortest_path is right is just a fluke.

For example, if we run the same code specifying `start = 1` and `end = 3` we obtain the following plot: 

``` r
# packages
library(stplanr)
library(sf)
library(igraph)

# Create the network structure 
routes <- st_sf(
  ID_from = c(101, 102, 103, 104, 101),
  ID_to = c(102, 103, 104, 101, 103), 
  ID_edge = 1:5, 
  distance = c(2.1, 1, 1.5, 2.5, 10),
  geometry = st_sfc(
    st_linestring(rbind(c(1, 3), c(3, 3))), 
    st_linestring(rbind(c(3, 3), c(3, 2))), 
    st_linestring(rbind(c(3, 2), c(2, 1))), 
    st_linestring(rbind(c(2, 1), c(1, 3))), 
    st_linestring(rbind(c(1, 3), c(3, 2)))
  )
)

# Create the sfNetwork object
sln <- SpatialLinesNetwork(routes)

# shortest path 
shortest <- sum_network_routes(sln, start = 1, end = 3, sumvars = c("length"))

# fastest path
E(sln@g)$weight <- routes$distance
sln@sl$length <- routes$distance

most_efficient <- sum_network_routes(sln, start = 1, end = 3, sumvars = c("length"))

plot(st_geometry(sln@sl))
plot(st_geometry(shortest), add = TRUE, col = "red", lwd = 2)
plot(st_geometry(most_efficient), add = TRUE, col = "blue", lwd = 2)
```

![](https://i.imgur.com/CDPUhN5.png)

<sup>Created on 2020-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

that should be right.  

It's not extremely difficult to solve this problem in this particular case (for example we can simply set `id <- V(sln@g)$name == start` and then subset `sln@g$x/y` according to this `id`) but the real question (for @Robinlovelace and everybody interested) is: what's the best and general solution? IMO, for the moment, we can just update the docs specifying that it's not possible to change the name of the Node ID(s) and then discuss how to proceed.

Happy to discuss this problem in the next days.  
 
---- 

I think that the problem with ``stplanr:::`weightfield<-`()`` for `sf` objects is here: 

https://github.com/ropensci/stplanr/blob/820791d679a9ef0359e71308d6b862829d1068ad/R/SpatialLinesNetwork.R#L318-L325

since we cannot use `sl@data` when `sl` is an `sf` object!

**Comment by Robinlovelace** [comment] 2020-04-27 05:33
Wow, thanks for such a detailed response @agila5. I will in detail at it at some point this week. In the meantime, @mnist91 is this of use for you? Great to see detailed discussion going on that leads to fundamental questions like 

> what's the best and general solution?

**Comment by mnist91** [comment] 2020-04-27 07:04
I am amazed by your persistent debugging and very detailed explanation of your findings, @agila5! 
Just for my personal understanding regarding my questions:

1. **How to define the nodes correctly?**
Use a mapping of node ID and node name. Yet, can I be sure that the automatically assigned node ID is always assigned sequentially as it occurs in the data? 

2. **How to derive the actual route?**
I am not sure what your proposed solution is for this. A mapping of route coordinates to node coordinates?

**Comment by agila5** [comment] 2020-04-27 09:06
Hi! I have several doubts but I think that the following answers could still be useful. 

> How to define the nodes correctly?

I'm not sure. Can you share more details on the original problem and the data? If the data are formatted as in the SO question, then I would suggest using `dodgr` approach. Moreover maybe you should also check the [`stplanr::route_local()`](https://docs.ropensci.org/stplanr/reference/route_local.html) function since the inputs are the coordinates of the nodes. 

> Yet, can I be sure that the automatically assigned node ID is always assigned sequentially as it occurs in the data?

Agan I don't know, I'm sorry. It's something that should be tested and discussed, especially for duplicated edges. 

> How to derive the actual route?

I'm not sure if I understand the question correctly, but I think that the actual route is the geometry component returned by the `sum_network_routes()`. This is the `sf` approach (where the actual route is the geometry column returned by that function): 

``` r
# packages
library(stplanr)
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union

# Create the network structure 
routes <- st_sf(
  ID_from = c(101, 102, 103, 104, 101),
  ID_to = c(102, 103, 104, 101, 103), 
  ID_edge = 1:5, 
  distance = c(2.1, 1, 1.5, 2.5, 10),
  geometry = st_sfc(
    st_linestring(rbind(c(1, 3), c(3, 3))), 
    st_linestring(rbind(c(3, 3), c(3, 2))), 
    st_linestring(rbind(c(3, 2), c(2, 1))), 
    st_linestring(rbind(c(2, 1), c(1, 3))), 
    st_linestring(rbind(c(1, 3), c(3, 2)))
  )
)

# Create the sfNetwork object
sln <- SpatialLinesNetwork(routes)

# shortest path 
shortest <- sum_network_routes(sln, start = 1, end = 3, sumvars = c("length"))
shortest # check the column called "geometry"
#> Simple feature collection with 1 feature and 3 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 2 xmax: 3 ymax: 3
#> CRS:            NA
#> # A tibble: 1 x 4
#>       geometry    ID sum_length pathfound
#>   <LINESTRING> <dbl>      <dbl> <lgl>    
#> 1   (1 3, 3 2)     1       2.24 TRUE

# fastest path
E(sln@g)$weight <- routes$distance
sln@sl$length <- routes$distance

most_efficient <- sum_network_routes(sln, start = 1, end = 3, sumvars = c("length"))
most_efficient # check the column called "geometry"
#> Simple feature collection with 1 feature and 3 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 2 xmax: 3 ymax: 3
#> CRS:            NA
#> # A tibble: 1 x 4
#>          geometry    ID sum_length pathfound
#>      <LINESTRING> <dbl>      <dbl> <lgl>    
#> 1 (1 3, 3 3, 3 2)     1        3.1 TRUE
```

<sup>Created on 2020-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

while this is the `sp` approach (where the actual route is the "@lines" slot): 

``` r
# packages
library(stplanr)
library(sp)
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union

# make up some dummy data that has the same structure as my original data 
routes <- data.frame(
  X_from = c(1, 3, 3, 2, 1),
  Y_from = c(3, 3, 2, 1, 3),
  X_to = c(3, 3, 2, 1, 3),
  Y_to = c(3, 2, 1, 3, 2),
  id_from = c(101, 102, 103, 104, 101),
  id_to = c(102, 103, 104, 101, 103),
  id_edge = 1:5,
  distance = c(2.1, 1, 1.5, 2.5, 10)
)

# convert it to the desired SpatialLinesNetwork format 
slines <- apply(routes, 1, function(x){
  l1 <- cbind(c(x["X_from"], x["X_to"]),
              c(x["Y_from"], x["Y_to"]))
  Sl1 <- Line(l1)
  S1 <- Lines(list(Sl1), ID = format(x["id_edge"], scientific = FALSE))
})
sl <- SpatialLines(slines)
df <- data.frame(len = routes[["distance"]])
rownames(df) <- as.character(routes$id_edge)
sldf <- SpatialLinesDataFrame(sl, df)
sln <- SpatialLinesNetwork(sldf)

# add an additional weight information to each edge
(sln@sl$weight <- routes$distance)
#> [1]  2.1  1.0  1.5  2.5 10.0

# shortest path
shortest <- sum_network_routes(
  sln = sln, 
  start = 1, end = 3, 
  sumvars = c("length", "weight")
)
shortest
#> class       : SpatialLinesDataFrame 
#> features    : 1 
#> extent      : 1, 3, 2, 3  (xmin, xmax, ymin, ymax)
#> crs         : NA 
#> variables   : 4
#> names       : ID,       sum_length, sum_weight, pathfound 
#> value       :  1, 2.23606797749979,         10,         1
shortest@lines # the actual route as a Line object
#> [[1]]
#> An object of class "Lines"
#> Slot "Lines":
#> [[1]]
#> An object of class "Line"
#> Slot "coords":
#>      [,1] [,2]
#> [1,]    1    3
#> [2,]    3    2
#> 
#> 
#> 
#> Slot "ID":
#> [1] "1"

# fastest path
weightfield(sln) <- "weight" # change weightfield
most_efficient <- sum_network_routes(
  sln = sln,
  start = 1, end = 3,
  sumvars = c("length", "weight")
) 
most_efficient
#> class       : SpatialLinesDataFrame 
#> features    : 1 
#> extent      : 1, 3, 2, 3  (xmin, xmax, ymin, ymax)
#> crs         : NA 
#> variables   : 4
#> names       : ID, sum_length, sum_weight, pathfound 
#> value       :  1,          3,        3.1,         1
# the actual route as a Line object. Note that it's different from previous route. 
most_efficient@lines 
#> [[1]]
#> An object of class "Lines"
#> Slot "Lines":
#> [[1]]
#> An object of class "Line"
#> Slot "coords":
#>      [,1] [,2]
#> [1,]    1    3
#> [2,]    3    3
#> [3,]    3    2
#> 
#> 
#> 
#> Slot "ID":
#> [1] "1"
```

<sup>Created on 2020-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Both examples use a "regular" node-ID approach (for the reasons described in the previous comment).

**Comment by mnist91** [comment] 2020-04-27 12:59
Thank you, this helps a lot! I really appreciate your effort!

Regarding my second question "How to retrieve my actual route?". My point was to get a path object as it is returned by igraph, where you get the approached nodes in their sequential order. However, I can also make use of the coordinates and join the node information onto them. This is fine but just requires more computationally intensive steps.

From this point on, I guess it will more efficient to use the raw igraph functionality and convert its result to the `sf` objects I need rather than using stplanr straight away. Nevertheless, I learnt a lot about stplanr and will likely come back to it at some point

**Comment by agila5** [comment] 2020-05-01 21:26
Hi @mnist91, I think we are quite close to a solution to this problem (something like `stplanr::find_network_nodes` + a named list of vertices). Tomorrow I will create another example and if you want you can check it.

**Comment by agila5** [comment] 2020-05-02 12:10
It's far from being ideal but it's a possible solution on how to match the IDs of the POINTS to the vertices: 

``` r
remotes::install_github("ropensci/stplanr")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'stplanr' from a github remote, the SHA1 (b2b95040) has not changed since last install.
#>   Use `force = TRUE` to force installation

# packages
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
library(stplanr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# create the network structure
routes <- st_sf(
  ID_from = c(101, 102, 103, 104, 101),
  ID_to = c(102, 103, 104, 101, 103), 
  ID_edge = 1:5, 
  distance = c(2.1, 1, 1.5, 2.5, 10),
  geometry = st_sfc(
    st_linestring(rbind(c(1, 3), c(3, 3))), 
    st_linestring(rbind(c(3, 3), c(3, 2))), 
    st_linestring(rbind(c(3, 2), c(2, 1))), 
    st_linestring(rbind(c(2, 1), c(1, 3))), 
    st_linestring(rbind(c(1, 3), c(3, 2)))
  )
)

# create the sln object
sln <- SpatialLinesNetwork(routes)

# Create a named list of vertices
vertices <- list()

for (i in seq_len(nrow(routes))) {
  my_ID_from <- as.character(routes$ID_from[[i]])
  if (is.null(vertices[[my_ID_from]])) {
    my_line <- st_geometry(routes)[[i]]
    point <- my_line[1, ]
    vertices[[my_ID_from]] <- point
  }
  
  my_ID_to <- as.character(routes$ID_to[[i]])
  if (is.null(vertices[[my_ID_to]])) {
    my_line <- st_geometry(routes)[[i]]
    point <- my_line[nrow(my_line), ]
    vertices[[my_ID_to]] <- point
  }
}
# result
vertices
#> $`101`
#> [1] 1 3
#> 
#> $`102`
#> [1] 3 3
#> 
#> $`103`
#> [1] 3 2
#> 
#> $`104`
#> [1] 2 1

# find the nearest vertices for each ID
cbind(names(vertices), find_network_nodes(sln, do.call("rbind", vertices)))
#>      [,1]  [,2]
#> [1,] "101" "1" 
#> [2,] "102" "2" 
#> [3,] "103" "3" 
#> [4,] "104" "4"
# Please note the input of sum_network_routes must be a numeric index
```

<sup>Created on 2020-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mnist91** [comment] 2020-05-02 14:18
Hi @agila5 Thanks again for your effort! I am really amazed by your persistence! Unfortunately, I already had to implement a reliable routing procedure so I used igraph and converted the results to an sf object. I am still a fan of stplanr in general and will definitely come back to it for another project.

**Comment by agila5** [comment] 2020-05-02 15:59
Ok great! @Robinlovelace I think you can close this for the moment.

**Comment by Robinlovelace** [comment] 2020-05-02 16:09
Thanks for all the feedback @mnist91, please close the issue if you're happy with the solution.

This issue has been beneficial for our thinking about and development of `stplanr` so feel free to raise any other issues you find. 

Regarding your solution, are you able to share the code? And have you checked-out the `sfnetworks` hackathon? You may want to pose a hackathon challenge, see this one for a routing one that I have created (also any comments on this of course welcome): https://github.com/luukvdmeer/sfnetworks/issues/46

**Closed** 2020-05-02 18:24 UTC
