### ISSUE TITLE
overline2 fails when knitting with version 0.5, but works with 0.3.1 

### ISSUE THREAD

**Issue by temospena** [ropensci/stplanr#380] opened 2020-02-09 13:38 UTC
I'm having a error with the overlne2 function at rmarkdown:
I was using stplanr version 0.3.1, and it was running fine when both running on step-by-step chunk, and using knit for the whole rmakdown script.

Bur when I updated to version 0.5, the error came as:
```
Error in st_geometry.sf(x) :
  attr(obj, "sf_column") does not point to a geometry column.
Did you rename it, without setting st_geometry(obj) <- "newname"?
Calls: <Anonymous> ... eval -> overline2 -> %in% -> <Anonymous> -> st_geometry.sf
```

The error only pops up when knit.

```
label: stplanr agregate (with options)
List of 6
 $ eval      : symbol T
 $ echo      : symbol T
 $ fig.height: num 4
 $ fig.width : num 5
 $ message   : logi FALSE
 $ warning   : logi FALSE

Quitting from lines 1799-1806 (COMPILACAO.Rmd)
Error in st_geometry.sf(x) :
  attr(obj, "sf_column") does not point to a geometry column.
Did you rename it, without setting st_geometry(obj) <- "newname"?
Calls: <Anonymous> ... eval -> overline2 -> %in% -> <Anonymous> -> st_geometry.sf

#here the Traceback
Error in st_geometry.sf(x) : attr(obj, "sf_column") does not point to a geometry column. Did you rename it, without setting st_geometry(obj) <- "newname"?
5. stop("attr(obj, \"sf_column\") does not point to a geometry column.\nDid you rename it, without setting st_geometry(obj) <- \"newname\"?")
4. st_geometry.sf(x)
3. sf::st_geometry(x)
2. "sfc_LINESTRING" %in% class(sf::st_geometry(x))
1. overline2(sl, "alunos")
```

I have the _sl_ as

```
> class(sl)
[1] "sf"         "data.frame"
> st_geometry(sl)
Geometry set for 102 features
geometry type:  LINESTRING
dimension:      XY
bbox:           xmin: -9.127613 ymin: 38.74525 xmax: -9.095069 ymax: 38.77941
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
First 5 geometries:
LINESTRING (-9.097722 38.77378, -9.098492 38.77...
LINESTRING (-9.117583 38.77072, -9.117653 38.77...
```

... so apparently is fine. 
I also tried ... to make sure that I was not using a different name for the geometry field
`st_geometry(sl) <- "geometry" #fine`

I rolled back to 0.3.1 version, and is working with no errors.

**Comment by Robinlovelace** [comment] 2020-02-18 15:43
I tried reproducing this but it works fine for me...

```
---
title: "Untitled"
output: html_document
---


   ```{r}
   library(stplanr)
  rnet = overline(routes_fast_sf, attrib = names(routes_fast_sf)[2])
   ```
```

**Comment by Robinlovelace** [comment] 2020-02-18 15:44
That's what I got:

Untitled
================

``` r
library(stplanr)
rnet = overline(routes_fast_sf, attrib = names(routes_fast_sf)[2])
```

    ## 2020-02-18 15:44:18 constructing segments

    ## 2020-02-18 15:44:18 building geometry

    ## 2020-02-18 15:44:18 simplifying geometry

    ## 2020-02-18 15:44:18 aggregating flows

    ## 2020-02-18 15:44:18 rejoining segments into linestrings

**Comment by Robinlovelace** [comment] 2020-04-17 21:13
Closing for now as cannot reproduce...

**Closed by Robinlovelace** 2020-04-17 21:13 UTC
