### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by nikolai-b** [ropensci/stplanr#59] opened 2016-01-21 22:09 UTC
I'm getting some strange aggregation issues.

From a node (Warrington 015) there are 36 cyclists but leaving but when I run overline on this I'm getting 56 on the only line that leaves that node.  Is the aggregation summing from other lines?  Maybe at a vertices?

**Comment by richardellison** [comment] 2016-01-24 04:40
@Robinlovelace might be better placed to look into this, but I have had a look and can't seem to reproduce the issue. The function removes any line segments where only the end points overlap but it is possible there is a problem with this. Can you provide a reproducible example?

**Comment by Robinlovelace** [comment] 2016-01-25 20:36
Will take a look later in the week.

**Comment by Robinlovelace** [comment] 2016-07-19 06:39
Closing - couldn't reproduce. @nikolai-b if you have any other issues with the function let us know - reproducible code appreciated. Cheers.

**Closed by Robinlovelace** 2016-07-19 06:39 UTC
