### ISSUE TITLE
add osmdata + bikedata example

### ISSUE THREAD

**Issue by mpadge** [ropensci/stplanr#194] opened 2017-06-02 14:20 UTC
code now at the end in the [bikedata vignette](https://mpadge.github.io/bikedata/articles/bikedata.html), thanks largely to @richardellison. This all works flawlessly with really impressive results. Note Richard, that your previous NYC example would also be very easy with the water polygons using `osmdata` - the vignette example merely had to be fast, and LA is simply much faster because of vastly less data.

Be great to see this code in the `stplanr` vignette too

**Comment by Robinlovelace** [comment] 2017-06-02 16:17
Really great to see the symbiosis between these 2 pkgs, thanks loads! This adds fuel to the #175 fire!

**Comment by richardellison** [comment] 2017-06-03 14:11
I will try doing a version of the New York example with `osmdata` instead now that I have added support for sf.

**Comment by richardellison** [comment] 2017-06-04 22:21
Using `osmdata` does work to replicate my New York example map. The result isn't exactly the same as when using original GIS layers primarily because the OSM streets are not always connected as they should be for a network so the shortest paths end up not being the actual shortest paths. Nonetheless, still works reasonably well:

![nyosmtest](https://cloud.githubusercontent.com/assets/10625733/26765839/a08ecca0-49c7-11e7-8941-98982be0f2e3.png)

```
store_bikedata (city = "ny", bikedb = 'bikedb', quiet = FALSE,dates = "201610")

stns <- bike_stations('bikedb',city = 'ny')
ntrips <- bike_tripmat('bikedb', city = 'ny', long = TRUE)

unknownstns <- stns[which(stns$longitude == 0 & stns$latitude == 0),]$stn_id
stns <- stns[which(!stns$stn_id %in% unknownstns),]
ntrips <- ntrips[which(!ntrips$start_station_id %in% unknownstns),]
ntrips <- ntrips[which(!ntrips$end_station_id %in% unknownstns),]

xlims_ny <- range(stns$longitude)
ylims_ny <- range(stns$latitude)

# expand those limits slightly
ex <- 0.1
xlims_ny <- xlims_ny + c (-ex, ex) * diff (xlims_ny)
ylims_ny <- ylims_ny + c (-ex, ex) * diff (ylims_ny)
bbox <- c (xlims_ny [1], ylims_ny [1], xlims_ny [2], ylims_ny [2])
# Then the actual osmdata query to extract all OpenStreetMap highways
highways <- osmdata::opq (bbox = bbox) %>%
  osmdata::add_feature (key = 'highway') %>% osmdata::osmdata_sf()

nynet <- SpatialLinesNetwork(highways$osm_lines)
nodeid <- find_network_nodes(nynet, stns$longitude, stns$latitude)

startid <- nodeid [match (ntrips$start_station_id, stns$stn_id)]
endid <- nodeid [match (ntrips$end_station_id, stns$stn_id)]
ntrips$start_station_id <- startid
ntrips$end_station_id <- endid

bike_usage <- sum_network_links (nynet, data.frame (ntrips))

waterways <- osmdata::opq(bbox = bbox) %>%
  osmdata::add_feature(key = 'waterway') %>% osmdata::osmdata_sf()

tm_shape(waterways$osm_multipolygons,
         bbox = matrix(c(-74.045141,40.681830,-73.92065,40.80502),nrow = 2)) + 
  tm_fill(col="#000011") + 
tm_shape(waterways$osm_polygons) + 
  tm_fill(col="#000011") + 
tm_shape(waterways$osm_lines) + 
  tm_lines(col="#000011") + 
tm_shape(bike_usage) + 
  tm_lines(col="numtrips",
           lwd="numtrips",
           title.col = "Number of trips",
           legend.lwd.show = FALSE,
           scale = 2) + 
tm_layout(
  bg.color = "black",
  legend.position = c("left","top"),
  legend.bg.color = "white",
  legend.bg.alpha = 0.5
)
```

**Comment by Robinlovelace** [comment] 2017-07-13 22:58
Heads-up @richardellison I could reproduce that awesome map with a modified version:

```r

library(bikedata)
store_bikedata (city = "ny", bikedb = 'bikedb', quiet = FALSE,dates = "201610")

stns <- bike_stations('bikedb',city = 'ny')
ntrips <- bike_tripmat('bikedb', city = 'ny', long = TRUE)

unknownstns <- stns[which(stns$longitude == 0 & stns$latitude == 0),]$stn_id
stns <- stns[which(!stns$stn_id %in% unknownstns),]
ntrips <- ntrips[which(!ntrips$start_station_id %in% unknownstns),]
ntrips <- ntrips[which(!ntrips$end_station_id %in% unknownstns),]

xlims_ny <- range(stns$longitude)
ylims_ny <- range(stns$latitude)

# expand those limits slightly
ex <- 0.1
xlims_ny <- xlims_ny + c (-ex, ex) * diff (xlims_ny)
ylims_ny <- ylims_ny + c (-ex, ex) * diff (ylims_ny)
bbox <- c (xlims_ny [1], ylims_ny [1], xlims_ny [2], ylims_ny [2])
# Then the actual osmdata query to extract all OpenStreetMap highways
highways <- osmdata::opq (bbox = bbox) %>%
  osmdata::add_feature (key = 'highway') %>% osmdata::osmdata_sf()
highways = as(object = highways$osm_lines, Class = "SpatialLines")
nynet <- SpatialLinesNetwork(highways)
nodeid <- find_network_nodes(nynet, stns$longitude, stns$latitude)

startid <- nodeid [match (ntrips$start_station_id, stns$stn_id)]
endid <- nodeid [match (ntrips$end_station_id, stns$stn_id)]
ntrips$start_station_id <- startid
ntrips$end_station_id <- endid

bike_usage <- sum_network_links (nynet, data.frame (ntrips))

waterways <- osmdata::opq(bbox = bbox) %>%
  osmdata::add_feature(key = 'waterway') %>% osmdata::osmdata_sf()

library(tmap)
tm_shape(waterways$osm_multipolygons,
         bbox = matrix(c(-74.045141,40.681830,-73.92065,40.80502),nrow = 2)) + 
  tm_fill(col="#000011") + 
  tm_shape(waterways$osm_polygons) + 
  tm_fill(col="#000011") + 
  tm_shape(waterways$osm_lines) + 
  tm_lines(col="#000011") + 
  tm_shape(bike_usage) + 
  tm_lines(col="numtrips",
           lwd="numtrips",
           title.col = "Number of trips",
           legend.lwd.show = FALSE,
           scale = 2) + 
  tm_layout(
    bg.color = "black",
    legend.position = c("left","top"),
    legend.bg.color = "white",
    legend.bg.alpha = 0.5
  )
```

**Comment by Robinlovelace** [comment] 2017-07-13 23:00
In the vignette now so closing - could be more prominent elsewhere so ideas where welcome.

**Closed by Robinlovelace** 2017-07-13 23:00 UTC

**Comment by mpadge** [comment] 2017-07-14 09:22
I'm still working on getting this probabilistic routing algorithm to behave in a stable fashion. When that comes together, all of these things can be synthesised nicely.
