### ISSUE TITLE
`rnet_merge()` fails when inputs are projected

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#549] opened 2023-10-04 20:09 UTC
As illustrated in the minimal reproducible example below. Heads-up @wangzhao0217 I think this may have been the issue you were hitting in #538 

``` r
library(stplanr)
library(sf)
#> Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
rnet_x = sf::read_sf("https://github.com/nptscot/npt/releases/download/v2/rnet_x_thurso.geojson")
rnet_y = sf::read_sf("https://github.com/nptscot/npt/releases/download/v2/rnet_y_thurso.geojson")

name_list = names(rnet_y)
funs = list()

# Loop through each name and assign it a function based on specific conditions
for (name in name_list) {
  if (name == "geometry") {
    next  # Skip the current iteration
  } else if (name %in% c("Gradient", "Quietness")) {
    funs[[name]] = mean
  } else {
    funs[[name]] = sum
  }
}

nrow(rnet_x)
#> [1] 913
nrow(rnet_y)
#> [1] 639

# Convert to projected geometry:
rnet_xp = st_transform(rnet_x, "EPSG:27700")
rnet_yp = st_transform(rnet_y, "EPSG:27700")

runtime = system.time({
  rnet_merged = rnet_merge(rnet_x, rnet_y, dist = 20, segment_length = 10, funs = funs, max_angle_diff = 20)
})
#> Warning: attribute variables are assumed to be spatially constant throughout
#> all geometries
#> Warning in st_cast.sf(sf::st_cast(x, "MULTILINESTRING"), "LINESTRING"):
#> repeating attributes for all sub-geometries for which they may not be constant
#> Joining with `by = join_by(identifier)`
#> Warning: st_centroid assumes attributes are constant over geometries
#> Joining with `by = join_by(identifier)`
# Segments per second:
nrow(rnet_x) / runtime[3]
#> elapsed 
#> 8.77623


# Convert to projected geometry:
rnet_xp = st_transform(rnet_x, "EPSG:27700")
rnet_yp = st_transform(rnet_y, "EPSG:27700")

runtime = system.time({
  rnet_merged = rnet_merge(rnet_xp, rnet_yp, dist = 20, segment_length = 10, funs = funs, max_angle_diff = 20)
})
#> Warning: attribute variables are assumed to be spatially constant throughout
#> all geometries

#> Warning: repeating attributes for all sub-geometries for which they may not be
#> constant
#> Joining with `by = join_by(identifier)`
#> Error in lwgeom::st_geod_azimuth(p[i:(i + 1)]): st_is_longlat(x) is not TRUE
```

<sup>Created on 2023-10-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by wangzhao0217** [comment] 2023-10-04 23:08
Hi Robin,
The issue with rnet_merge() still persists. I added more places for testing:
```{r}
points_of_interest = c("Thurso", "Girlsta",  "Edinburgh")
```
![image](https://github.com/ropensci/stplanr/assets/74598734/09dac608-db65-48e2-a0d6-9fb8e862181d)

At Edinburgh, works perfectly!
![image](https://github.com/ropensci/stplanr/assets/74598734/bdd7d725-9ce3-47eb-ad2f-9c1926ae5eb4)
but no results for Thurso and Girlsta
![image](https://github.com/ropensci/stplanr/assets/74598734/0389ae9f-fb0e-4784-91ff-6af4bd659c9a)
![image](https://github.com/ropensci/stplanr/assets/74598734/513dbeac-1693-45d6-97bb-f04dea56068e)

**Comment by Robinlovelace** [comment] 2023-10-05 05:03
Thanks Zhao, this is a good description of the consequence of this issue. Will work on it.

**Comment by wangzhao0217** [comment] 2023-10-05 11:40
Hi Robin,
I found the issue is related to rnet_subset(), not rnet_merge().  Executing the code yields the correct results:
```{r}
rnet_merged = rnet_merge(rnet_x, rnet_y, dist = 20, segment_length = 10, funs = funs, max_angle_diff = 20, crs = "EPSG:27700",subset_x = FALSE) 
```

![image](https://github.com/ropensci/stplanr/assets/74598734/d193b511-58e9-4e02-9def-9cecd793808d)
![image](https://github.com/ropensci/stplanr/assets/74598734/067c8230-86cd-4074-894c-92ca9d3dfb92)

I will close this issue open other one.

**Closed by wangzhao0217** 2023-10-05 11:40 UTC

**Comment by Robinlovelace** [comment] 2023-10-05 11:48
Yes: that makes sense. Try without running `rnet_subset()`?
